module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/*.test.ts',
    '!src/**/*.spec.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  moduleNameMapping: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@/app$': '<rootDir>/src/app',
    '^@/server$': '<rootDir>/src/server',
    '^@/config/(.*)$': '<rootDir>/src/config/$1',
    '^@/constants/(.*)$': '<rootDir>/src/constants/$1',
    '^@/controllers/(.*)$': '<rootDir>/src/controllers/$1',
    '^@/dao/(.*)$': '<rootDir>/src/dao/$1',
    '^@/db/(.*)$': '<rootDir>/src/db/$1',
    '^@/interfaces/(.*)$': '<rootDir>/src/interfaces/$1',
    '^@/logger/(.*)$': '<rootDir>/src/logger/$1',
    '^@/middleware/(.*)$': '<rootDir>/src/middleware/$1',
    '^@/routes/(.*)$': '<rootDir>/src/routes/$1',
    '^@/services/(.*)$': '<rootDir>/src/services/$1',
    '^@/types/(.*)$': '<rootDir>/src/types/$1',
    '^@/utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@/validators/(.*)$': '<rootDir>/src/validators/$1',
    '^@/tests/(.*)$': '<rootDir>/src/__tests__/$1',
    '^@/test/(.*)$': '<rootDir>/test/$1',
    '^@/prisma/(.*)$': '<rootDir>/prisma/$1',
    '^@/environment/(.*)$': '<rootDir>/environment/$1',
  },
};
